name: Working with Artifacts
on: 
    workflow_dispatch:     

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: my-app
        steps:      
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.x'

            - name: Cache
              id: cache
              uses: actions/cache@v4
              with:
                path: my-app/node_modules
                key: ${{hashFiles('my-app/package-lock.json')}}
           
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                npm ci
                  
            - name: Build code
              run: |
                npm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: my-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - test-build
        steps:
            - run: echo "test build"
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: build
                path: my-app/build